version: '3.8'
name: 'superbrains'
volumes:
  sb_redis_data:
  sb_postgres_data:
services:
  redis:
    image: redis:7.2
    restart: 'no'
    container_name: sb_redis
    command: --loglevel notice
    volumes:
      - sb_redis_data:/data
    ports:
      - 6379:6379
  postgres:
    image: postgres:14-bullseye
    container_name: sb_postgres
    command: -c log_statement=all
    restart: 'no'
    depends_on:
      - redis
    volumes:
      - sb_postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - PGPASSWORD=postgres
      - POSTGRES_DB=dev
    ports:
      - 5432:5432
  # pgadmin:
  #   image: dpage/pgadmin4
  #   restart: "no"
  #   depends_on:
  #   - postgres
  #   ports:
  #   - 5050:80
  #   environment:
  #     PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
  #     PGADMIN_DEFAULT_PASSWORD: admin
