version: '3'
services:
  api:
    image: ghcr.io/paiteq/hlp-api:production
    container_name: hlp-api
    ports:
      - '3000:3000'
      - '3001:3001'
    restart: always
    command:
      - /bin/bash
      - -c
      - npm run start:prod
    deploy:
      mode: replicated
      replicas: 1
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      - DOPPLER_TOKEN=${DOPPLER_TOKEN}
