import { ConfigModuleOptions } from '@nestjs/config';
import Joi from 'joi';

export enum Environment {
  PODUCTION = 'production',
  DEVELOPMENT = 'development',
  STAGING = 'staging',
  LOCAL = 'local',
}

export const configValidations = Joi.object().keys({
  PORT: Joi.number().default(3000),
  NODE_ENV: Joi.string()
    .equal(...Object.values(Environment))
    .default('development'),
  API_TOKEN: Joi.string().required(),
  JWT_SECRET: Joi.string().required(),
  JWT_EXPIRATION: Joi.string().default('3d'),
  THROTTLE_LIMIT: Joi.number().default(60),
  THROTTLE_TTL: Joi.number().default(60),
  HASURA_ADMIN_SECRET: Joi.string().required(),
  HASURA_URL: Joi.string().uri().required(),
  AWS_S3_BUCKET: Joi.string().required(),
  AWS_ACCESS_KEY: Joi.string().required(),
  AWS_SECRET: Joi.string().required(),
  AWS_REGION: Joi.string().required(),
  IMAGEKIT_BASE_URL: Joi.string().uri().required(),
  REDIS_HOST: Joi.string().required(),
  REDIS_PASSWORD: Joi.string().required(),
  REDIS_PORT: Joi.number().required(),
  STRIPE_SECRET_KEY: Joi.string().required(),
  STRIPE_WEBHOOK_SECRET: Joi.string().required(),
  CURRENCY: Joi.string().required(),
  FIREBASE_WEB_API_KEY: Joi.string().required(),
  FIREBASE_DOMAIN_URI_PREFIX: Joi.string().required(),
  ONESIGNAL_APP_KEY: Joi.string().required(),
  ONESIGNAL_APP_ID: Joi.string().required(),
  POSTGRES_URL: Joi.string(),
  AWS_SES_VERIFIED_EMAIL: Joi.string().required(),
  APP_PACKAGE_NAME: Joi.string().required(),
  PUK_KEY: Joi.string().required(),
  TEST_USER_EMAIL: Joi.string().email(),
  PUK_TEST_ID: Joi.string().default('PTS'),
  HTTP_BASIC_AUTH_USERNAME: Joi.string().default('admin'),
  HTTP_BASIC_AUTH_PASSWORD: Joi.string().default('735TS6LaVH'),
  SENTRY_DSN: Joi.string().required(),
  ONESIGNAL_ANDROID__NOTIFICATION_CHANNELS: Joi.string(),
  WEB_URL: Joi.string().uri().required(),
  ADMIN_AUTH_TOKEN: Joi.string().required(),
  I18N_FALLBACK_LANG: Joi.string().default('en'),
  DOCTOR_WEB_URL: Joi.string().uri().required(),
  TAX_PERCENTAGE: Joi.number().required(),
  SHIPPING_CHARGES: Joi.number().required(),
  JITSI_TOKEN_EXPIRATION_IN_MINUTES: Joi.string().required(),
  JITSI_APP_ID: Joi.string().required(),
  JITSI_HOST: Joi.string().required(),
  WS_PORT: Joi.number().required(),
  TEMP_JWT_SECRET: Joi.string().required(),
  APP_STORE_ID: Joi.string().required(),
  MOLLIE_API_KEY: Joi.string().required(),
  MOLLIE_WEBHOOK_URL: Joi.string().uri().required(),
  OAUTH_API_TOKEN: Joi.string().required(),
  MAILCHIMP_API_KEY: Joi.string().required(),
  MAILCHIMP_SERVER_PREFIX: Joi.string().required(),
  MAILCHIMP_LIST_ID: Joi.string().required(),
  DOWNLOAD_APP_URL: Joi.string().required(),
  BRANCH_IO_API_URL: Joi.string().required(),
  BRANCH_IO_API_KEY: Joi.string().required(),
  DIGID_LOGIN_URL: Joi.string().required(),
  DIGID_CERTIFICATE_PASSPHRASE: Joi.string().required(),
  DIGID_CERTIFICATE: Joi.string().required(),
  DIGID_REDIRECT_URL: Joi.string().required(),
  DIGID_CLIENT_SECRET: Joi.string().required(),
  DIGID_CLIENT_ID: Joi.string().required(),
  DIGID_OAUTH2_URL: Joi.string().required(),
  APP_URI_SCHEME: Joi.string().required(),
  OTEL_TRACE_URL: Joi.string().uri(),
  OTEL_METRIC_URL: Joi.string().uri(),
  ENABLE_OTEL: Joi.boolean(),
  PSYQ_URL: Joi.string().required(),
  PSYQ_CERT: Joi.string().required(),
  PSYQ_CACERT: Joi.string().required(),
  PSYQ_KEY: Joi.string().required(),
});

export const configOptions: ConfigModuleOptions = {
  isGlobal: true,
  validationSchema: configValidations,
  validationOptions: {
    abortEarly: false,
  },
};

export enum EnvVariable {
  ONESIGNAL_APP_ID = 'ONESIGNAL_APP_ID',
  ONESIGNAL_APP_KEY = 'ONESIGNAL_APP_KEY',
  POSTGRES_URL = 'POSTGRES_URL',
  NODE_ENV = 'NODE_ENV',
  PORT = 'PORT',
  AWS_SES_VERIFIED_EMAIL = 'AWS_SES_VERIFIED_EMAIL',
  AWS_ACCESS_KEY = 'AWS_ACCESS_KEY',
  AWS_SECRET = 'AWS_SECRET',
  AWS_REGION = 'AWS_REGION',
  CURRENCY = 'CURRENCY',
  APP_PACKAGE_NAME = 'APP_PACKAGE_NAME',
  PUK_KEY = 'PUK_KEY',
  TEST_USER_EMAIL = 'TEST_USER_EMAIL',
  PUK_API_URL = 'PUK_API_URL',
  REDIS_HOST = 'REDIS_HOST',
  REDIS_PASSWORD = 'REDIS_PASSWORD',
  REDIS_PORT = 'REDIS_PORT',
  PUK_TEST_ID = 'PUK_TEST_ID',
  HTTP_BASIC_AUTH_USERNAME = 'HTTP_BASIC_AUTH_USERNAME',
  HTTP_BASIC_AUTH_PASSWORD = 'HTTP_BASIC_AUTH_PASSWORD',
  SENTRY_DSN = 'SENTRY_DSN',
  ONESIGNAL_ANDROID__NOTIFICATION_CHANNELS = 'ONESIGNAL_ANDROID__NOTIFICATION_CHANNELS',
  WEB_URL = 'WEB_URL',
  ADMIN_AUTH_TOKEN = 'ADMIN_AUTH_TOKEN',
  I18N_FALLBACK_LANG = 'I18N_FALLBACK_LANG',
  DOCTOR_WEB_URL = 'DOCTOR_WEB_URL',
  TAX_PERCENTAGE = 'TAX_PERCENTAGE',
  SHIPPING_CHARGES = 'SHIPPING_CHARGES',
  JITSI_TOKEN_EXPIRATION_IN_MINUTES = 'JITSI_TOKEN_EXPIRATION_IN_MINUTES',
  JITSI_APP_ID = 'JITSI_APP_ID',
  JITSI_HOST = 'JITSI_HOST',
  WS_PORT = 'WS_PORT',
  TEMP_JWT_SECRET = 'TEMP_JWT_SECRET',
  APP_STORE_ID = 'APP_STORE_ID',
  CUSTOMER_SUPPORT_EMAIL = 'CUSTOMER_SUPPORT_EMAIL',
  SESSION_FORM_ID = 'SESSION_FORM_ID',
  COMPLAINT_FORM_ID = 'COMPLAINT_FORM_ID',
  MOLLIE_API_KEY = 'MOLLIE_API_KEY',
  MOLLIE_WEBHOOK_URL = 'MOLLIE_WEBHOOK_URL',
  OAUTH_API_TOKEN = 'OAUTH_API_TOKEN',
  MAILCHIMP_API_KEY = 'MAILCHIMP_API_KEY',
  MAILCHIMP_SERVER_PREFIX = 'MAILCHIMP_SERVER_PREFIX',
  MAILCHIMP_LIST_ID = 'MAILCHIMP_LIST_ID',
  DOWNLOAD_APP_URL = 'DOWNLOAD_APP_URL',
  BRANCH_IO_API_URL = 'BRANCH_IO_API_URL',
  BRANCH_IO_API_KEY = 'BRANCH_IO_API_KEY',
  DIGID_LOGIN_URL = 'DIGID_LOGIN_URL',
  DIGID_CLIENT_ID = 'DIGID_CLIENT_ID',
  DIGID_CLIENT_SECRET = 'DIGID_CLIENT_SECRET',
  DIGID_REDIRECT_URL = 'DIGID_REDIRECT_URL',
  DIGID_CERTIFICATE = 'DIGID_CERTIFICATE',
  DIGID_CERTIFICATE_PASSPHRASE = 'DIGID_CERTIFICATE_PASSPHRASE',
  DIGID_OAUTH2_URL = 'DIGID_OAUTH2_URL',
  APP_URI_SCHEME = 'APP_URI_SCHEME',
  OTEL_TRACE_URL = 'OTEL_TRACE_URL',
  OTEL_METRIC_URL = 'OTEL_METRIC_URL',
  ENABLE_OTEL = 'ENABLE_OTEL',
  PSYQ_URL = 'PSYQ_URL',
  PSYQ_CERT = 'PSYQ_CERT',
  PSYQ_CACERT = 'PSYQ_CACERT',
  PSYQ_KEY = 'PSYQ_KEY',
}
