import {
  Field,
  GraphQLISODateTime,
  ObjectType,
  registerEnumType,
} from '@nestjs/graphql';

export enum AppointmentType {
  INTAKE = 'INTAKE',
  RESEARCH = 'RESEARCH',
  OTHER = 'OTHER',
  INDIVIDUAL_CONSULTATION_CLIENT_DIAGNOSTICS = 'INDIVIDUAL_CONSULTATION_CLIENT_DIAGNOSTICS',
  SOMATIC_SCREENING_OR_PHYSICAL_EXAMINATION = 'SOMATIC_SCREENING_OR_PHYSICAL_EXAMINATION',
  DIAGNOSTIC_CONSULTATION_WITH_LOVED_ONES = 'DIAGNOSTIC_CONSULTATION_WITH_LOVED_ONES',
  CONSULTATION_EUTHANASIA_REQUESTS = 'CONSULTATION_EUTHANASIA_REQUESTS',
  INDIVIDUAL_CONSULTATION_CLIENT_TREATMENT = 'INDIVIDUAL_CONSULTATION_CLIENT_TREATMENT',
  INDIVIDUAL_CONSULTATION_CLIENT_AND_LOVED_ONES = 'INDIVIDUAL_CONSULTATION_CLIENT_AND_LOVED_ONES',
  INDIVIDUAL_CONSULTATION_WITH_LOVED_ONES = 'INDIVIDUAL_CONSULTATION_WITH_LOVED_ONES',
  MDO_WITH_CLIENT = 'MDO_WITH_CLIENT',
  GROUP_CONSULTATION_CLIENTS = 'GROUP_CONSULTATION_CLIENTS',
  GROUP_CONSULTATION_WITH_LOVED_ONES = 'GROUP_CONSULTATION_WITH_LOVED_ONES',
  ECT = 'ECT',
  SUBJECT_THERAPY = 'SUBJECT_THERAPY',
  GMAP_CRISIS_ASSESSMENT = 'GMAP_CRISIS_ASSESSMENT',
  CRISIS_CONSULTATION_DIAGNOSTICS = 'CRISIS_CONSULTATION_DIAGNOSTICS',
  CRISIS_CONSULTATION_TREATMENT = 'CRISIS_CONSULTATION_TREATMENT',
  DAY_CARE_SOCIAL = 'DAY_CARE_SOCIAL',
  DAY_CARE_ACTIVATION = 'DAY_CARE_ACTIVATION',
  DAY_CARE_EDUCATION = 'DAY_CARE_EDUCATION',
  DAY_CARE_OCCUPATIONAL = 'DAY_CARE_OCCUPATIONAL',
  MULTIDISCIPLINARY_CONSULTATION_WITHOUT_A_CLIENT = 'MULTIDISCIPLINARY_CONSULTATION_WITHOUT_A_CLIENT',
  INDIRECT_CLIENT_RELATED_TIME = 'INDIRECT_CLIENT_RELATED_TIME',
}
registerEnumType(AppointmentType, { name: 'AppointmentType' });

@ObjectType()
export class UserAppointment {
  id: string;
  user_id: string;
  doctor_id: string;
  appointment_type: AppointmentType;
  location: string;
  note?: string;
  session_form_enabled: boolean;
  complaint_form_enabled: boolean;
  psyq_appointment_id?: string;
  @Field(() => GraphQLISODateTime)
  created_at: Date;
  @Field(() => GraphQLISODateTime)
  updated_at: Date;
}
