name: superbrains-dev

on:

  push:

    branches:

      - main

  workflow_dispatch:
 
env:

  REGISTRY: ghcr.io

  IMAGE_NAME: ${{ github.repository }}

  username: ${{ github.actor }}

  password: ${{ secrets.TOKEN }}
 
jobs:

  build:

    runs-on: ubuntu-latest

    permissions:

      contents: read

      packages: write
 
    steps:

      - name: Checkout repository

        uses: actions/checkout@v3

      - name: build and push docker image

        run: |

          export CR_PAT=${{ secrets.TOKEN }}

          echo $CR_PAT | docker login ghcr.io -u USERNAME --password-stdin

          docker pull ghcr.io/${GITHUB_REPOSITORY}:develop || true

          docker build --tag ghcr.io/${GITHUB_REPOSITORY}:develop .

          docker push ghcr.io/${GITHUB_REPOSITORY}:develop
